language: java

  #    addons:
  #      sonarcloud:
  #        organization: "https-github-com-yanncb"
  #        token:
  #          secure: "6972d88da70bff63384a311d143aa020b36e065e" # encrypted value of your token
  #
  #    script:
  #      # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  #      - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=https-github-com-yanncb-p9
  after_success:
    - bash <(curl -s https://codecov.io/bash)
  env:
    global:
      - CODECOV_TOKEN=:uuid-repo-token